# Generated by Django 5.1.6 on 2026-06-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='color',
            field=models.CharField(blank=True, default='#7c3aed', max_length=20),
        ),
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
